# Enter how the number 1000 should be displayed
format: "$1,000.00"
name-singular: "coin"
name-plural: "coins"

redis:
  enabled: false
  host: ""
  port: ""

#single-currency:
  # material: "GOLD_NUGGET"
  # name: "Gold Nugget"
  # lore: []

#nine-currency:
#  material: "GOLD_INGOT"
#  name: "Gold Ingot"
#  lore: []

#eighty-one-currency:
#  material: "GOLD_BLOCK"
#  name: "Gold Block"
#  lore: []
