# Enter how the number 1000 should be displayed
format: "$1,000.00"
name-singular: "coin"
name-plural: "coins"

prevent-interaction: false # stops players from using the item
prevent-placing: false # stops players from placing the items on the ground as blocks
custom-crafting: false

logging: false

redis:
  enabled: false # if false, it will use flat file storage
#  host: ""
#  port: ""

single-currency:
   material: "EMERALD"
  # name: ""
  # lore: []

nine-currency:
  material: "EMERALD_BLOCK"
#  name: "Gold Ingot"
#  lore: []

eighty-one-currency:
  material: "LODESTONE"
#  name: "Gold Block"
#  lore: []
