author: Multitallented
database: false
description: Allows you to create structures and towns.
main: org.redcastlemedia.multitallented.physicalcurrency.PhysicalCurrency
name: PhysicalCurrency
load: STARTUP
version: 1.0.0
api-version: 1.14
depend: [Vault]
commands:
  pcurr:
    aliases: ['money', 'bal']
    description: Physical Currency commands
    usage: /<command> [set|add|sub] [player] [amount]
  pay:
    description: Pay another user
    usage: /<command>
permissions:
  pcurr.pay:
    description: Allows players to pay other players
    default: false
  pcurr.admin:
    description: Lets you use admin commands
    default: op
loadafter: [Vault]
